name: CI-CD
on:
    push:
    workflow_dispatch:

jobs:

    CI:
        runs-on: ubuntu-latest
        steps:
        -   name: Obtendo o código
            uses: actions/checkout@v4.1.5
        -   name: Autenticação no Docker Hub
            uses: docker/login-action@v3.1.0
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        -   name: Build da Imagem Docker
            uses: docker/build-push-action@v5.3.0
            with:
                context: ./src
                file: ./src/Dockerfile
                push: true
                tags: |
                    thiagolange/aula-primeira-pipeline:v${{ github.run_number }}
                    thiagolange/aula-primeira-pipeline:latest

    CD-homolog:
        needs: [CI]
        uses: ThiagoLange/primeiro-pipeline_ci_cd/.github/workflows/deploy.yml@main
        with:
            manifests: |
                k8s/deployment.yaml
            images: |
                thiagolange/aula-primeira-pipeline:v${{ github.run_number }}
            environment: homologacao
        secrets: inherit

    Teste-Ambiente:
        needs: [CD-homolog]
        runs-on: ubuntu-latest+
        environment: homologacao
        steps:
            -   name: Fake Test
                run: echo "Fake teste de ambiente ${{ vars.APP_NAMESPACE }}"

       
    CD-producao:
        needs: [Teste-Ambiente]
        uses: ThiagoLange/primeiro-pipeline_ci_cd/.github/workflows/deploy.yml@main
        with:
            manifests: |
                k8s/deployment.yaml
            images: |
                thiagolange/aula-primeira-pipeline:v${{ github.run_number }}
            environment: producao
        secrets: inherit

